# Mostly based on Eric Niebler's range-v3 one: 
# https://github.com/ericniebler/range-v3/blob/master/.travis.yml

language: cpp
script: cmake

matrix:
  include:
    - env: BUILD_TYPE=Release CLANG_VERSION=3.7
      os: linux
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - libclang-dev # For DRLParser
            - g++-5 # We need an updated stdlibc++ for clang too
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - env: BUILD_TYPE=Debug CLANG_VERSION=3.7
      os: linux
      addons: *clang37

    - env: BUILD_TYPE=Release GCC_VERSION=5.3.0 GCC=gcc-5 GXX=g++-5
      os: linux
      addons: &gcc530
        apt:
          packages:
            - libclang-dev # We need libclang for reflection parser
            - g++-5
            - gcc-5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - env: BUILD_TYPE=Debug GCC_VERSION=5.3.0 GCC=gcc-5 GXX=g++-5
      os: linux
      addons: *gcc530

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="$GXX" CC="$GCC"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [ "$CLANG_VERSION" == "3.4" ]; then export CXX="/usr/local/clang-3.4/bin/clang++" CC="/usr/local/clang-3.4/bin/clang"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - $CC --version

install:

# From Louis Dionne's Boost.Hana .travis.yml

############################################################################
# All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

############################################################################
# Install a recent CMake
############################################################################
  - CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
  - mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

  - cmake --version
  - cd ${TRAVIS_BUILD_DIR}

  # Install reflection parser dependencies:
  - pip install --user -r include/reflection/parser/requirements.txt

  # Configure and build project:
  - if [ ! -d build ]; then mkdir build; fi
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDRLPARSER_IGNORE_DATABASE=TRUE
  - cmake --build .

script:
  - ctest . -VV
  - make run_CPP
