# Mostly based on Eric Niebler's range-v3 one: 
# https://github.com/ericniebler/range-v3/blob/master/.travis.yml

language: cpp
script: cmake

matrix:
  include:
    - env: BUILD_TYPE=Release CLANG_VERSION=3.4
      os: linux
      addons: &clang34
        apt:
          packages:
            - clang-3.4
          sources:
            - ubuntu-toolchain-r-test

    - env: BUILD_TYPE=Debug CLANG_VERSION=3.4
      os: linux
      addons: *clang34

    - env: BUILD_TYPE=Release GCC_VERSION=4.9
      os: linux
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - env: BUILD_TYPE=Debug GCC_VERSION=4.9
      os: linux
      addons: *gcc49

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [ "$CLANG_VERSION" == "3.4" ]; then export CXX="/usr/local/clang-3.4/bin/clang++" CC="/usr/local/clang-3.4/bin/clang"; fi
  - which $CXX
  - which $CC

install:
  - if [ ! -d build ]; then mkdir build; fi
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build .

script:
  - ctest . -VV
