# Setup
title:        siplasplas
tagline:      A library for C++ reflection and introspection
baseurl:      "/siplasplas"
paginate:     1	
highlighter: rouge

# About/contact
author:
  name:       Manu Sánchez
  url:        https://manu343726.github.io

# project data
project:
  name: siplasplas
  desc: A library for C++ relection and introspection
  url: https://github.com/Manu343726/siplasplas
  website: https://manu343726/github.io/siplasplas
  issues:
    url: https://github.com/Manu343726/siplasplas/issues
  documentation:
    doxygen:
      - name: master
        url: master
      - name: feature/typeerasure
        url: feature__slash__type-erasure
    standardese:
      - name: master
        url: master
      - name: feature/typeerasure
        url: feature__slash__type-erasure
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
