# Setup
title:        siplasplas
tagline:      A library for C++ reflection and introspection
baseurl:      "siplasplas"
paginate:     1

# About/contact
author:
  name:       Manu Sánchez
  url:        https://manu343726.github.io/siplasplas

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown