version: 1.0.{build}

environment:
  GCCGenerator: "MinGW Makefiles"
  matrix:
#    - generator: "Visual Studio 11 2012"
#    - generator: "Visual Studio 12 2013"
    - generator: "Visual Studio 14 2015"

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: choco install cmake 
  - cmd: if "%generator%" == "%GCCGenerator%" choco install mingw > nul # The mingw installer is in verbose mode, see https://chocolatey.org/packages/mingw
  - cmd: cmake --version
  - cmd: if "%generator%" == "%GCCGenerator%" g++ --version

build_script:
  - cmd: IF NOT EXIST build mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%generator%" -DCMAKE_BUILD_TYPE="%configuration%"
  - cmd: cmake --build . --config "%configuration%"

test_script:
  - cmd: ctest -C "%configuration%" . -VV
  - cmd: cmake --build . --target run-examples-all
  - cmd: cmake --build . --target package # TODO: Deploy to gihtub


