version: 1.0.{build}

environment:
  GCCGenerator: "Unix Makefiles"
  MinGWURL: " http://nuwen.net/files/mingw/mingw-13.4-without-git.exe"
  matrix:
#    - generator: "Visual Studio 11 2012"
#    - generator: "Visual Studio 12 2013"
    - generator: "Visual Studio 14 2015"
    - generator: "%GCCGenerator%"

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init
  - cmd: choco install cmake 
  - cmd: if "%generator%" == "%GCCGenerator%" curl -o mingw.exe 
  - cmd: if "%generator%" == "%GCCGenerator%" mingw.exe -y -gm2 -InstallPath="C:\MinGW" 
  - cmd: cmake --version
  - cmd: if "%generator%" == "%GCCGenerator%" g++ --version

build_script:
  - cmd: IF NOT EXIST build mkdir build
  - cmd: cd build
  - cmd: cmake .. -G "%generator%" -DCMAKE_BUILD_TYPE="%configuration%"
  - cmd: cmake --build . --config "%configuration%"

test_script:
  - cmd: ctest -C "%configuration%" . -VV
  - cmd: cmake --build . --target run_CPP